---
- hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - test_vars.yml

  tasks:
    - block:

        ## Generating the testname for deployment
        - include_tasks: /utils/fcm/create_testname.yml

         ## RECORD START-OF-TEST IN LITMUS RESULT CR
        - include_tasks: "/utils/fcm/update_litmus_result_resource.yml"
          vars:
            status: 'SOT'
   
        - name: Replace the storage capacity placeholder
          replace:
              path: "{{ application_deployment }}"
              regexp: "volume-capacity"
              replace: "{{ lookup('env','CAPACITY') }}" 

        - block:

            ## Actual test
            ## Creating namespaces and making the application for deployment
            - include_tasks: /utils/k8s/pre_create_app_deploy.yml
        
            ## Deploying the application, upper bound wait time: 900s 
            - include_tasks: /utils/k8s/deploy_single_app.yml
              vars:
                check_app_pod: 'yes'
                delay: 5 
                retries: 180
    
            ## Fetching the pod name
            - include_tasks: /utils/k8s/fetch_app_pod.yml
    
            ## Checking the db is ready for connection
            - include_tasks: /utils/scm/applications/mysql/check_db_connection.yml
   
            ## Check application-target pod affinity
            - include_tasks: /utils/scm/openebs/target_affinity_check.yml
              when: lookup('env','TARGET_AFFINITY_CHECK') == 'enable'

            - set_fact:
                flag: "Pass"  

          when: "'deprovision' not in action"  

        - block:

            - name: Deprovisioning the Application
              include_tasks: "/utils/k8s/deprovision_deployment.yml"
              vars:
                app_deployer: "{{ application_deployment }}"

            - set_fact:
                flag: "Pass"  

          when: "'deprovision' is in action"        

      rescue:
        - set_fact:
            flag: "Fail"     

      always:
            ## RECORD END-OF-TEST IN LITMUS RESULT CR
        - include_tasks: /utils/fcm/update_litmus_result_resource.yml
          vars:
            status: 'EOT'
              
