---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: litmus-openebs-provision-
  namespace: litmus
spec:
  template:
    metadata:
      name: litmus
      labels:
        app: openebs-provision
    spec:
      serviceAccountName: litmus
      restartPolicy: Never
      containers:
      - name: ansibletest
        image: openebs/ansible-runner:ci
        imagePullPolicy: Always

        env:
          - name: ANSIBLE_STDOUT_CALLBACK
            #value: log_plays, actionable, default
            value: default

            # OpenEBS Version
          - name: RELEASE_VERSION
            value: ""
            
            # Namespace where OpenEBS is deployed
          - name: OPERATOR_NS
            value: ""

            #  Image tag for NDM
          - name: NDM_TAG
            value: ""

          - name: DEPLOY_TYPE
            value: ""

          - name: ACTION
            value: provision 

        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./providers/openebs/installers/operator/openebs-provision/test.yml -i /etc/ansible/hosts -v; exit 0"]