---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-cstor-cvr-scale
  annotations:
    openebs.io/cas-type: cstor
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: "spc-name"
      - name: ReplicaCount
        value: "replica-count"
provisioner: openebs.io/provisioner-iscsi