# Description:
#      OpenEBS volume snapshot creation and restoring it to the earlier state.
# Author: Giri
# Prerequisites: Application should have been deployed in K8s cluster.

#########################################################################################################
# Test steps:                                                                                           #
# Create LitmusResult CR.                                                                               #
# Obtain volume name using the app label and app namespace provided as envs.                            #
# Create a database and a table.                                                                        #
# Obtain maya-apiserver pod name and create snapshot.                                                   #
# Modify the database.                                                                                  #
# Restore the volume using the snapshot created.                                                        #
# Check the data retention post restore.                                                                #
# Update the LitmusResult CR.                                                                           #
#                                                                                                       #
#########################################################################################################

- hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - test_vars.yml

  tasks:

   - block:

       - block:

           - name: Record test instance/run ID.
             set_fact:
               run_id: "{{ lookup('env','RUN_ID') }}"

           - name: Construct testname appended with runID.
             set_fact:
               test_name: "{{ test_name }}-{{ run_id }}"

         when: lookup('env','RUN_ID')

              ## RECORD START-OF-TEST IN LITMUS RESULT CR
       - include_tasks: /utils/fcm/update_litmus_result_resource.yml
         vars:
           status: 'SOT'

       - name: Checking the status  of test specific namespace.
         shell: kubectl get namespaces {{ app_ns }} -o jsonpath='{.status.phase}'
         args:
          executable: /bin/bash
         register: ns_status
         until: "'Active' in ns_status.stdout"
         delay: 30
         retries: 10

       - name: Obtaining the application pod name using its label.
         shell: >
           kubectl get pods -n {{ app_ns }} -l {{ app_label }}
           --no-headers -o custom-columns=:metadata.name
         args:
           executable: /bin/bash
         register: app_pod

       - name: Obtaining pvc name using the application pod name.
         shell: >
           kubectl get pod {{ app_pod.stdout }} -n {{ app_ns }}
           -o custom-columns=:..claimName --no-headers
         args:
           executable: /bin/bash
         register: pvc_name

       - name: Obtaining PV name using application PVC name.
         shell: >
           kubectl get pvc {{ pvc_name.stdout }} -n {{ app_ns }}
           -o custom-columns=:spec.volumeName --no-headers
         args:
           executable: /bin/bash
         register: volume_name

       - name: setting volume name to a variable.
         set_fact:
           volume_name: "{{ volume_name.stdout }}"

       - name: Setting pod name to a variable.
         set_fact:
           pod_name: "{{ app_pod.stdout }}"

       - name: Write a test database into percona mysql.
         shell: |
           kubectl exec -it {{ pod_name }} -n {{ app_ns }} -- mysql -u{{ user_name }} -p{{ password }} -e "create database tdb;"
           kubectl exec -it {{ pod_name }} -n {{ app_ns }} -- mysql -u{{ user_name }} -p{{ password }} -e "create table ttbl (Data VARCHAR(20));" tdb
           kubectl exec -it {{ pod_name }} -n {{ app_ns }} -- mysql -u{{ user_name }} -p{{ password }} -e "insert into ttbl (Data) VALUES ('tdata');" tdb
           kubectl exec -it {{ pod_name }} -n {{ app_ns }} -- mysql -u{{ user_name }} -p{{ password }} -e "flush tables with read lock;"
         args:
           executable: /bin/bash
         register: result
         failed_when: "result.rc != 0"

       - name: Performing file system sync on percona pod before creating the snapshot.
         shell: kubectl exec {{ pod_name }} -n {{ app_ns }} -- bash -c "sync;sync;sync"
         args:
           executable: /bin/bash

       # Here, we include openebs_snapshot_restore.yml from litmus funclib for creating snapshot.

       - name: Creating snapshot.
         include_tasks: /funclib/openebs/openebs_snapshot_restore.yml
         vars:
           action: create_snapshot

       - name: Make changes to the database created.
         shell: |
           kubectl exec -it {{ pod_name }} -n {{ app_ns }} -- mysql -u{{user_name}} -p{{ password }} -e "unlock tables;"
           kubectl exec -it {{ pod_name }} -n {{ app_ns }} -- mysql -u{{user_name}} -p{{ password }} -e "drop database tdb"
           sleep 10
         args:
           executable: /bin/bash
         register: result
         failed_when: "result.rc != 0"

         #Here we include funclib utility to restore the volume

       - name: Restoring the volume data using snapshot.
         include_tasks: /funclib/openebs/openebs_snapshot_restore.yml
         vars:
           action: restore_snapshot

       - name: Delete the application pod to force volume remount upon rescheduling.
         shell: kubectl delete pod {{pod_name}} -n {{ app_ns }}
         args:
           executable: /bin/bash
         register: result
         failed_when: "pod_name and 'deleted' not in result.stdout"

       - name: Checking if the application pod is scheduled again
         shell: kubectl get pod -n {{ app_ns }} -l {{ app_label }}
         args:
           executable: /bin/bash
         register: result
         until: "'Running' in result.stdout"
         delay: 30
         retries: 15

       - name: Obtaining application pod details after restart.
         shell: >
           kubectl get pods -n {{ app_ns }} -l {{ app_label }} -o custom-columns=:.metadata.name
           --no-headers
         args:
           executable: /bin/bash
         register: result

       - name: Store new percona pod name in variable.
         set_fact:
           pod_name: "{{ result.stdout }}"

       - name: Verifying whether the restore operation is successful by validating data.
         shell: >
           kubectl exec -it {{ pod_name }} -n {{ app_ns }} -- mysql -u{{ user_name }} -p{{ password }}
           -e "select * from ttbl;" tdb
         args:
           executable: /bin/bash
         register: result
         failed_when: "'tdata' not in result.stdout"

       - name: Test Passed
         set_fact:
           flag: "Test Passed"

     rescue:
       - name: Test Failed
         set_fact:
           flag: "Test Failed"

     always:

        ## RECORD END-OF-TEST IN LITMUS RESULT CR

       - include_tasks: /utils/fcm/update_litmus_result_resource.yml
         vars:
           status: 'EOT'
