---
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: minio
  namespace: velero
spec:
  provider: openebs.io/cstor-blockstore
  config:
      bucket: velero
      provider: aws
      region: minio
      s3ForcePathStyle: "true"
      s3Url: http://minio.velero.svc:9000