---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: litmus-jiva-csi-provisioner-
  namespace: litmus
spec:
  template:
    metadata:
      name: litmus
      labels:
        app: jiva-csi-provisioner
    spec:
      serviceAccountName: litmus
      restartPolicy: Never
      containers:
      - name: ansibletest
        image: openebs/ansible-runner:ci
        imagePullPolicy: Always
        env:
          - name: ANSIBLE_STDOUT_CALLBACK
            #value: log_plays
            value: default

          - name: OPERATOR_IMAGE
            value: ci

          - name: PROVIDER_STORAGE_CLASS
            value: openebs-jiva-csi-sc
          
          - name: NODE_OS
            value: ubuntu-16.04

          - name: REPLICA_SC
            value: openebs-hostpath

          - name: REPLICA_COUNT
            value: "3"

          - name: ACTION
            value: provision  

        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./providers/jiva-csi-provisioner/test.yml -i /etc/ansible/hosts -v; exit 0"]
