---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: litmus-jiva-csi-provisioner-
  namespace: litmus
spec:
  template:
    metadata:
      name: litmus
      labels:
        provider: jiva-operator
    spec:
      serviceAccountName: litmus
      restartPolicy: Never
      containers:
      - name: ansibletest
        image: openebs/ansible-runner:ci
        imagePullPolicy: Always
        env:
          - name: ANSIBLE_STDOUT_CALLBACK
            #value: log_plays
            value: default

          - name: OPERATOR_IMAGE
            value: ci

          - name: REPLICA_SC
            value: local-pv-hostpath

          - name: REPLICA_COUNT
            value: "3"

          - name: ACTION
            value: provision

          - name: POOL_PATH
            value: "/var/openebs/local"

        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./providers/jiva-csi-provisioner/test.yml -i /etc/ansible/hosts -vv; exit 0"]
