---
- hosts: localhost
  connection: local

  vars_files:
    - test_vars.yml

  tasks:
    - block:

      ## Generating the testname for deployment
        - include_tasks: /utils/fcm/create_testname.yml

         ## RECORD START-OF-TEST IN LITMUS RESULT CR
        - include_tasks: "/utils/fcm/update_litmus_result_resource.yml"
          vars:
            status: 'SOT'

        - name: Generate yaml files to create storage class
          template:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
          with_items:
             - { src: cstor-xfs-sc.j2,dest: cstor-xfs-sc.yml }
             - { src: jiva-xfs-sc.j2,dest: jiva-xfs-sc.yml }
             - { src: cstor-volume-monitor-sc.j2,dest: cstor-volume-monitor-sc.yml }
             - { src: cstor-disk-standalone.j2,dest: cstor-disk-standalone.yml }
             - { src: local-pv-hostpath.j2,dest: local-pv-hostpath.yml }
             - { src: cstor-perf-parameters.j2,dest: cstor-perf-parameters.yml }
             - { src: cstor-cvr-scale.j2,dest: cstor-cvr-scale.yml }

        - block:

            - name: Create storage classes with specific storage policies
              shell: kubectl apply -f {{ item }}
              args:
                executable: /bin/bash
              register: sc
              with_items:
                - "{{ storage_policies }}"

            - name: Confirm that the storage classes are created
              shell: kubectl get storageclass
              args:
                executable: /bin/bash
              register: result_sc
              until: '"{{ item }}" in result_sc.stdout'
              delay: 15
              retries: 5
              with_items:
                - openebs-cstor-xfs
                - openebs-jiva-xfs
                - openebs-cstor-volume-monitor
                - cstor-disk-standalone
                - openebs-jiva-standalone
                - local-pv-hostpath
                - cstor-performance-config
                - jiva-openebs-ns
                - openebs-cstor-cvr-scale

          when: lookup('env','ACTION') == 'create'

        - block:
        
            - name: Delete storage classes with specific storage policies
              shell: kubectl delete -f {{ item }}
              args:
                executable: /bin/bash
              register: sc
              with_items:
                - "{{ storage_policies }}"

            - name: Confirm that the storage classes are deleted
              shell: kubectl get storageclass
              args:
                executable: /bin/bash
              register: result_sc
              until: '"{{ item }}" not in result_sc.stdout'
              delay: 15
              retries: 5
              with_items:
                - openebs-cstor-xfs
                - openebs-jiva-xfs
                - openebs-cstor-volume-monitor
                - local-pv-hostpath
                - cstor-disk-standalone
                - openebs-jiva-standalone
                - cstor-performance-config                
                - jiva-openebs-ns
                - openebs-cstor-cvr-scale

          when: lookup('env','ACTION') == 'delete'

        - set_fact:
            flag: "Pass"

      rescue:
        - set_fact:
            flag: "Fail"

      always:
            ## RECORD END-OF-TEST IN LITMUS RESULT CR
        - include_tasks: /utils/fcm/update_litmus_result_resource.yml
          vars:
            status: 'EOT'

