---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: cstor-cspc-pool-expansion-
  namespace: litmus
spec:
  template:
    metadata:
      name: litmus
      labels:
        app: cstor-cspc-pool-expansion
    spec:
      serviceAccountName: litmus
      restartPolicy: Never
      containers:
      - name: ansibletest
        image: openebs/ansible-runner:ci
        imagePullPolicy: Always

        env:
          - name: ANSIBLE_STDOUT_CALLBACK
            #value: log_plays, actionable, default
            value: default

            # Provide name POOL_NAME to expand
          - name: POOL_NAME
            value: cstor-cspc-disk-pool

           # Provide the value for POOL_TYPE to expand
          - name: POOL_TYPE
            value: stripe

          - name: OPERATOR_NS
            value: openebs

        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./providers/cstor/cstor-cspc-pool-expansion/test.yml -i /etc/ansible/hosts -v; exit 0"]
