apiVersion: v1
kind: Service
metadata:
  labels:
    lkey: lvalue
  name: busybox
spec:
  clusterIP: None
  selector:
    lkey: lvalue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-busybox
  labels:
    lkey: lvalue
    affinity_label: lvalue
spec:
  serviceName: busybox
  selector:
    matchLabels:
      lkey: lvalue
      affinity_label: lvalue
  template:
    metadata:
      labels:
        lkey: lvalue
        affinity_label: lvalue
    spec:
      containers:
      - name: app-busybox
        imagePullPolicy: IfNotPresent
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 10;done"]
        env:
        volumeMounts:
        - name: data-vol
          mountPath: /busybox
      volumes:
      - name: data-vol
        persistentVolumeClaim:
          claimName: testclaim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: testclaim
  labels:
    affinity_label: lvalue
spec:
  storageClassName: testclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: teststorage