apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  name: pool-name
spec:
  name: pool-name
  type: disk
  maxPools: maxpool-count
  poolSpec:
    poolType: pool-type
    thickProvisioning: false
  blockDevices:
    blockDeviceList:

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-name
  annotations:
    openebs.io/cas-type: cstor
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: pool-name
      - name: ReplicaCount
        value: "3"
provisioner: openebs.io/provisioner-iscsi
