# Description:  Creates a Virtual Private Cloud with the name openebs-e2e, that will be specified
# with all other clusters. Using --subnet-mode=auto will create a subnet for every zone. This file
# is ran at the begining of e2e tests
# Author: Harshvardhan Karn
###############################################################################################
#Steps:
#1. Create a VPC, openebs-e2e in Google Cloud
###############################################################################################

---
- hosts: localhost
  tasks:
       - block:

             - name: Generating Random VPC Name
               shell: python ../../utils/name_generator/namesgenerator.py
               register: vpc
             - set_fact:
                 vpc: "{{ vpc.stdout }}"
             - name: Creating VPC
               shell: gcloud compute --project={{ project }} networks create {{ vpc }} --subnet-mode=auto

             - lineinfile:
                 create: yes
                 state: present
                 path: "~/logs/vpc"
                 line: "{{ vpc }}"

             - name: Test Passed
               set_fact:
                 flag: "Test Passed"
         rescue:
             - name: Test Failed
               set_fact:
                 flag: "Test Failed"